import base64
import io
from fpdf import FPDF
from backend.report_generator import ReportRequest

class ReportPDF(FPDF):
    def header(self):
        # Title
        self.set_font('helvetica', 'B', 20)
        self.set_text_color(255, 255, 255)  # White text
        # Dark background for header
        self.set_fill_color(13, 17, 23)  # #0d1117
        self.rect(0, 0, 210, 40, 'F')
        
        self.set_xy(10, 10)
        self.cell(0, 10, 'Engineering Audit Report', new_x="LMARGIN", new_y="NEXT", align='L', fill=False)
        
        self.set_font('helvetica', 'I', 10)
        self.set_text_color(139, 148, 158) # Muted Text
        self.cell(0, 5, 'Generated by Spatial Engine - AI-Assisted Physics Analysis', new_x="LMARGIN", new_y="NEXT", align='L', fill=False)
        self.ln(15)

    def footer(self):
        self.set_y(-15)
        self.set_font('helvetica', 'I', 8)
        self.set_text_color(128)
        self.cell(0, 10, f'Page {self.page_no()} | Spatial Engine v0.3.0', align='C')

    def chapter_title(self, label):
        self.set_font('helvetica', 'B', 14)
        self.set_text_color(88, 166, 255) # Accent Color
        self.cell(0, 10, label, new_x="LMARGIN", new_y="NEXT", align='L')
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(5)

    def chapter_body(self, body):
        self.set_font('helvetica', '', 11)
        self.set_text_color(0)
        self.multi_cell(0, 5, body)
        self.ln()

    def metric_card(self, label, value, x, y, width=45):
        self.set_xy(x, y)
        self.set_fill_color(240, 240, 240)
        self.rect(x, y, width, 25, 'F')
        
        self.set_xy(x, y + 5)
        self.set_font('helvetica', 'B', 14)
        self.set_text_color(0)
        self.cell(width, 7, str(value), align='C', new_x="LMARGIN", new_y="NEXT")
        
        self.set_xy(x, y + 14)
        self.set_font('helvetica', '', 8)
        self.set_text_color(100)
        self.cell(width, 5, label, align='C')

def generate_pdf_report(data: ReportRequest) -> bytes:
    pdf = ReportPDF()
    pdf.add_page()
    
    # 1. Executive Summary
    pdf.chapter_title('Executive Summary')
    
    # Metrics Grid
    start_y = pdf.get_y()
    pdf.metric_card("Audited Area", f"{data.area_sqm} m²", 10, start_y)
    pdf.metric_card("Avg Illuminance", f"{data.lux_level} lx", 60, start_y)
    pdf.metric_card("Pot. Annual Savings", f"${data.energy_savings_annual}", 110, start_y)
    pdf.metric_card("ROI Payback", f"{data.payback_months} mo", 160, start_y)
    pdf.ln(35)

    # 2. Visual Analysis
    pdf.chapter_title('Visual Light Analysis')
    
    pdf.set_font('helvetica', 'B', 11)
    pdf.set_text_color(0)
    pdf.cell(0, 8, "Simulation Heatmap (Physics Engine)", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font('helvetica', '', 10)
    pdf.multi_cell(0, 5, "Calculated light distribution based on Inverse Square Law.")
    pdf.ln(2)

    if data.physics_heatmap_image:
        try:
            img_data = base64.b64decode(data.physics_heatmap_image)
            img_stream = io.BytesIO(img_data)
            pdf.image(img_stream, x=10, w=190)
            pdf.ln(5)
        except Exception as e:
            pdf.cell(0, 10, f"Error loading physics heatmap: {str(e)}", new_x="LMARGIN", new_y="NEXT")
    else:
         pdf.cell(0, 10, "No simulation data available.", new_x="LMARGIN", new_y="NEXT")
    
    pdf.ln(10)
    
    # Vision Audit
    if pdf.get_y() > 220: pdf.add_page() # Page break if needed for next image

    pdf.set_font('helvetica', 'B', 11)
    pdf.cell(0, 8, "Photon Distribution Map (Vision Audit)", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font('helvetica', '', 10)
    pdf.multi_cell(0, 5, "Computer Vision analysis of the physical space with overlaid distribution grid.")
    pdf.ln(2)

    if data.vision_heatmap_image:
        try:
            img_data = base64.b64decode(data.vision_heatmap_image)
            img_stream = io.BytesIO(img_data)
            pdf.image(img_stream, x=10, w=190)
            pdf.ln(5)
        except Exception as e:
            pdf.cell(0, 10, f"Error loading vision heatmap: {str(e)}", new_x="LMARGIN", new_y="NEXT")
    else:
         pdf.cell(0, 10, "No vision audit data available.", new_x="LMARGIN", new_y="NEXT")

    pdf.ln(10)

    # 3. Economic Forecast
    if pdf.get_y() > 200: pdf.add_page()
    
    pdf.chapter_title('Economic Forecast (ROI)')
    pdf.multi_cell(0, 5, "Projected return on investment comparing current lighting configuration vs. recommended high-efficiency upgrades.")
    pdf.ln(5)
    
    # ROI Charts side by side
    y_pos = pdf.get_y()
    
    if data.roi_chart_image:
        try:
            img_data = base64.b64decode(data.roi_chart_image)
            img_stream = io.BytesIO(img_data)
            pdf.image(img_stream, x=10, y=y_pos, w=90)
        except:
             pdf.text(10, y_pos + 10, "Error loading ROI chart")
    
    if data.consumption_chart_image:
        try:
            img_data = base64.b64decode(data.consumption_chart_image)
            img_stream = io.BytesIO(img_data)
            pdf.image(img_stream, x=110, y=y_pos, w=90)
        except:
            pdf.text(110, y_pos + 10, "Error loading Consumption chart")

    return bytes(pdf.output())
