import json
import base64
from datetime import datetime
from typing import Optional, Dict, Any
from pydantic import BaseModel

class ReportRequest(BaseModel):
    project_name: str = "Spatial Engine Audit"
    timestamp: str = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    
    # Metrics
    area_sqm: float
    lux_level: float
    target_lux: float
    energy_savings_annual: Optional[float] = 0.0
    co2_reduction: Optional[float] = 0.0
    payback_months: Optional[float] = 0.0
    
    # Images (Base64 strings)
    physics_heatmap_image: Optional[str] = None
    vision_heatmap_image: Optional[str] = None
    roi_chart_image: Optional[str] = None

def generate_html_report(data: ReportRequest) -> str:
    """
    Generates a standalone HTML engineering report with embedded base64 images.
    """
    
    # CSS Styles
    styles = """
    <style>
        :root {
            --bg-color: #0d1117;
            --card-bg: #161b22;
            --text-main: #c9d1d9;
            --text-muted: #8b949e;
            --accent: #58a6ff;
            --border: #30363d;
            --success: #2ea043;
            --warning: #d29922;
        }
        body {
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif;
            background-color: var(--bg-color);
            color: var(--text-main);
            margin: 0;
            padding: 40px;
            line-height: 1.5;
        }
        .container {
            max-width: 900px;
            margin: 0 auto;
        }
        header {
            border-bottom: 1px solid var(--border);
            padding-bottom: 20px;
            margin-bottom: 40px;
            display: flex;
            justify-content: space-between;
            align-items: center;
        }
        h1 { margin: 0; color: white; }
        .meta { color: var(--text-muted); font-size: 0.9em; }
        
        .section {
            margin-bottom: 40px;
            background: var(--card-bg);
            border: 1px solid var(--border);
            border-radius: 6px;
            padding: 24px;
        }
        .section-title {
            margin-top: 0;
            margin-bottom: 20px;
            font-size: 1.25em;
            color: var(--accent);
            border-bottom: 1px solid var(--border);
            padding-bottom: 10px;
        }
        
        .metrics-grid {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
            gap: 20px;
        }
        .metric-card {
            background: rgba(255,255,255,0.05);
            padding: 15px;
            border-radius: 4px;
            text-align: center;
        }
        .metric-value {
            display: block;
            font-size: 1.8em;
            font-weight: bold;
            color: white;
            margin-bottom: 5px;
        }
        .metric-label {
            color: var(--text-muted);
            font-size: 0.85em;
            text-transform: uppercase;
            letter-spacing: 1px;
        }
        
        .chart-container {
            width: 100%;
            text-align: center;
            margin-top: 20px;
            background: #000;
            padding: 10px;
            border-radius: 4px;
        }
        img {
            max-width: 100%;
            height: auto;
            border-radius: 4px;
        }
        
        .footer {
            margin-top: 60px;
            text-align: center;
            color: var(--text-muted);
            font-size: 0.8em;
            border-top: 1px solid var(--border);
            padding-top: 20px;
        }
    </style>
    """
    
    # HTML Structure
    html = f"""
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>{data.project_name} - Report</title>
        {styles}
    </head>
    <body>
        <div class="container">
            <header>
                <div>
                    <h1>Engineering Audit Report</h1>
                    <div class="meta">Generated by Spatial Engine • AI-Assisted Physics Analysis</div>
                </div>
                <div class="meta">
                    Date: {data.timestamp}
                </div>
            </header>
            
            <!-- EXECUTIVE SUMMARY -->
            <div class="section">
                <h2 class="section-title">Executive Summary</h2>
                <div class="metrics-grid">
                    <div class="metric-card">
                        <span class="metric-value">{data.area_sqm} m²</span>
                        <span class="metric-label">Audited Area</span>
                    </div>
                    <div class="metric-card">
                        <span class="metric-value" style="color: {'var(--success)' if data.lux_level >= data.target_lux else 'var(--warning)'}">{data.lux_level} lx</span>
                        <span class="metric-label">Avg Illuminance</span>
                    </div>
                    <div class="metric-card">
                        <span class="metric-value">${data.energy_savings_annual}</span>
                        <span class="metric-label">Pot. Annual Savings</span>
                    </div>
                    <div class="metric-card">
                        <span class="metric-value">{data.payback_months} mo</span>
                        <span class="metric-label">ROI Payback</span>
                    </div>
                </div>
            </div>
            
            <!-- VISUAL ANALYSIS -->
            <div class="section">
                <h2 class="section-title">Visual Light Analysis</h2>
                
                <h3 style="color:white; font-size:1.1em; margin-bottom:10px;">Simulation Heatmap (Physics Engine)</h3>
                <p>Calculated light distribution based on Inverse Square Law.</p>
                {f'<div class="chart-container"><img src="data:image/png;base64,{data.physics_heatmap_image}" alt="Physics Heatmap"></div>' if data.physics_heatmap_image else '<p style="color:var(--text-muted)">No simulation data available.</p>'}

                <div style="margin-top:30px;">
                    <h3 style="color:white; font-size:1.1em; margin-bottom:10px;">Photon Distribution Map (Vision Audit)</h3>
                    <p>Computer Vision analysis of the physical space with overlaid distribution grid.</p>
                    {f'<div class="chart-container"><img src="data:image/png;base64,{data.vision_heatmap_image}" alt="Vision Heatmap"></div>' if data.vision_heatmap_image else '<p style="color:var(--text-muted)">No vision audit data available.</p>'}
                </div>
            </div>
            
            <!-- ECONOMIC ANALYSIS -->
            <div class="section">
                <h2 class="section-title">Economic Forecast (ROI)</h2>
                <p>Projected return on investment comparing current lighting configuration vs. recommended high-efficiency upgrades.</p>
                
                {f'<div class="chart-container"><img src="data:image/png;base64,{data.roi_chart_image}" alt="ROI Chart"></div>' if data.roi_chart_image else '<p style="color:var(--text-muted)">No ROI chart available.</p>'}
            </div>
            
            <div class="footer">
                <p>Spatial Engine v0.3.0 | Certified for Internal Engineering Use</p>
            </div>
        </div>
    </body>
    </html>
    """
    
    return html
